services:
  postgres:
    image: postgres:16-alpine
    container_name: cortex_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - cortex
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  cortex:

volumes:
  postgres_data: