spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
      hibernate:
        sql: DEBUG
server:
  port: ${SPRING_PORT:8080}